"""added columns in profile model

Revision ID: 7b192ea21c4b
Revises: 7524d7fe429b
Create Date: 2025-04-07 17:42:58.107284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b192ea21c4b'
down_revision: Union[str, None] = '7524d7fe429b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('profiles', sa.Column('place', sa.String(length=100), nullable=True))
    op.add_column('profiles', sa.Column('clinic_name', sa.String(length=100), nullable=True))
    op.add_column('profiles', sa.Column('consultation_fee', sa.Integer(), nullable=True))
    op.add_column('profiles', sa.Column('experience', sa.Integer(), nullable=True))
    op.add_column('profiles', sa.Column('description', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'description')
    op.drop_column('profiles', 'experience')
    op.drop_column('profiles', 'consultation_fee')
    op.drop_column('profiles', 'clinic_name')
    op.drop_column('profiles', 'place')
    op.drop_column('profiles', 'city')
    # ### end Alembic commands ###
