"""added email and mobile unique constraint

Revision ID: 7bc720eea955
Revises: 767100f1e8bf
Create Date: 2025-03-21 15:36:55.092395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bc720eea955'
down_revision: Union[str, None] = '767100f1e8bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'profiles', ['mobile'])
    op.create_unique_constraint(None, 'profiles', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'profiles', type_='unique')
    op.drop_constraint(None, 'profiles', type_='unique')
    # ### end Alembic commands ###
